info:
  component: Eureka Service Discovery Client

server:
  port: 8090

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/