info:
  component: springboot actuator endpoints
  contact:
    email: admin@wajahat.com
    phone: 1-700-762-9879

server:
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    platform: h2

management:
  context-path: /manage
  health:
    sensitive: true
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true

security:
  user:
    name: admin
    password: s3cr3t
    role: ADMIN

endpoints:
  health:
    enabled: true
  shutdown:
    enabled: true
  restart:
    enabled: true
  beans:
    sensitive: true