info:
  app:
    name: spring-jpamysql-movies-api
    description: Implementing Movies api with Spring JPA, Hibernate and MySQL

server:
  port: 9999

management:
  context-path: /manage
  security:
    enabled: false

endpoints:
  health:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false

#debug: true

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/spring_wajahat_demo?autoReconnect=true&useSSL=false
    username: root
    password: Welcome123
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    dialect: org.hibernate.dialect.MySQL5Dialect