info:
  app:
    name: spring-jpamysql-movies-api
    description: Implementing Movies api with Spring JPA, Hibernate and MySQL

server:
  port: 9999

#debug: true

spring:
  datasource:
    url:  jdbc:mysql://107.108.52.79:3306/spring_boot_demo
    username: root
    password: 786SaMSaW
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    dialect: org.hibernate.dialect.MySQL5Dialect